# Generated by Django 4.1.1 on 2022-09-12 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="Books",),
    ]
